// src/lib/supabaseClient.ts
//
// Single Supabase client for the public app.
// Uses the ANON key only (safe for client-side).
// Types come from `src/types/supabase.ts` generated by `supabase gen types`.
//

import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types/supabase';

// Vite exposes env vars at build-time via import.meta.env.
// These MUST be set in `.env` (or your deployment environment).
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

// We pass <Database> so `.from('profiles')` etc become fully typed.
// This keeps the app honest and avoids "stringly-typed" table access.
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);